# LGMVIP:Beginner Level Task:
# Task 1:Iris Flowers Classification ML Project:

# Author: Abdulmuiz Shaikh

In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
df=pd.read_csv("iris.csv")

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [5]:
#Seperating variables
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [6]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [7]:
#Splitting data in train test split
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3, random_state=42)

In [8]:
#Used Logistic Regression for prediction
model = LogisticRegression()
#fitting model
model.fit(xtrain, ytrain) 

LogisticRegression()

In [9]:
#getting predictions,and classification report
predictions = model.predict(xtest)
print("Predictions:\n",predictions)

print("\n\n", classification_report(ytest, predictions) )

print("\nThe accuracy is:", accuracy_score(ytest, predictions))

Predictions:
 ['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa'
 'setosa' 'setosa' 'setosa' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'virginica' 'setosa' 'virginica' 'setosa' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'setosa' 'setosa' 'virginica' 'versicolor'
 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'setosa']


               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


The accuracy is: 1.0


In [10]:
#confusion matrix
confmat = confusion_matrix(ytest,predictions)
print("Confusion Matrix:\n",confmat)

Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
